### ISSUE TITLE
DIN5 connector

### ISSUE THREAD

**Issue by kentforth** [tttapa/Control-Surface#109]
Hello Pieter!
If I want to send midi cc not through usb but through DIN5 connector. 
**What should I change in code to make it happen?**
**What pins on Arduino should I use for DIN5 connector?**

**Comment by tttapa** [comment]
You can use the following instead of the `USBMIDI_Interface`:
```cpp
HardwareSerialMIDI_Interface midi = Serial1;
```
Replace `Serial1` with whatever UART you want to use. This depends on the board you're using, so you'll have to look at the pinout and documentation for your specific board.

For example, on an Arduino Leonardo, the hardware UART is `Serial1`, and the correct pins are `0` (RX) and `1` (TX).

**Comment by kentforth** [comment]
Thank you!
