### ISSUE TITLE
How is debounce done?

### ISSUE THREAD

**Issue by shaunchu** [tttapa/Control-Surface#312]
Hello @tttapa,

I see you mentioned you're using PaulStoffregen's encoder library, and when using your Control-Surface library the rotary encoders are fantastic, accurate without latency. 

"All digital inputs are debounced, and all analog inputs are filtered using digital filters and hysteresis. This results in high accuracy without noise, without introducing latency."

But trying PaulStoffregen's encoder library examples gives bouncing results. Do you mind pointing me to where you modified his code to do software debounce?

Thanks!

**Comment by tttapa** [comment]
There's no debouncing for rotary encoders, only for buttons and switches, so I suspect the problem lies elsewhere. The only thing that Control Surface does to the encoder input is dividing it by 4, to get one “tick” per physical click of the encoder. You can find the full implementation here: 

https://github.com/tttapa/Control-Surface/blob/0efe4a882766894e4e82d5736e4927e92b9d7f41/src/MIDI_Outputs/Abstract/MIDIRotaryEncoder.hpp#L44-L51

As you can see, it simply reads the PJRC Encoder library position, computes the difference with the previous position, divides it by 4 (by default), sends it over MIDI, and updates the previous position.
